Fix Grafana proxy configuration
oVirt/ovirt-dwh pull request #38
Opened 2022-05-18 15:11 UTC by avlitman

There is a grafana update in version 7.5.15 used on CS8.
We need to pass the original Host and Origin headers from the client request to Grafana.

Signed-off-by: Aviv Litman <alitman@redhat.com>

2022-05-18 15:20 UTC, avlitman commented
/ost basic-suite-master el8stream

2022-05-18 17:38 UTC, mwperina requested changes
The change itself looks good to me, please check if it works not only with the new grafana versions 7.5.15 but also with older 7.5.11. And if so, we should also handle upgrade (during engine-setup we need to check if ProxyPreserveHost on line exists in the file and if not, then the file needs to be updated).

2022-05-19 05:45 UTC, didib approved these changes
Looks good to me, from packaging/setup POV. I didn't investigate the actual issue nor do I know all the implications of using ProxyPreserveHost.

2022-05-19 05:46 UTC, didib commented
"Looks good to me" means: I checked the relevant code and it seems like it should work also on upgrades. Please verify this.

2022-05-19 09:24 UTC, michalskrivanek approved these changes

2022-05-19 10:29 UTC, avlitman commented
> please check if it works not only with the new grafana versions 7.5.15 but also with older 7.5.11. 

Verified on rhel8 Grafana 7.5.11

2022-05-19 12:52 UTC, avlitman commented
> we should also handle upgrade (during engine-setup we need to check if ProxyPreserveHost on line exists in the file and if not, then the file needs to be updated).

Verified on upstream+downstream upgrades, engine-setup recreates the file (the only step needed is to upgrade and run engine-setup).

2022-05-19 13:14 UTC, mwperina approved these changes
+1

2022-05-19 13:58 UTC, merged